spring.application.name=1.StudentFrontEnd
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/frontendStudent
spring.datasource.username=root
spring.datasource.password=Praveen@06

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true